language: php

php:
  - 7.2

services: mongodb

sudo: false

before_install:
  - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install --no-interaction --prefer-source

before_script:
  - sleep 15

script: vendor/bin/phpunit