version: '3'

services:

#  test:
#    build: .
#    depends_on:
#      - database

  database:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: testing